### ISSUE TITLE
AttributeError: module 'mkdocs.utils' has no attribute 'string_types' on mkdocs build

### ISSUE THREAD

**Issue by nehatharani** [zayd62/mkdocs-versioning#37]
**Describe the bug**
I followed the instructions and created docs. My folder structure looks like this: 

work_docs\
     docs\
       index.md
       tring.md
     site\
     mkdocs.yml

when I try to do mkdocs build it throws the error: AttributeError: module 'mkdocs.utils' has no attribute 'string_types' on mkdocs build

**To Reproduce**
mkdocs.yml: 
```
site_name: My Docs
theme: 'material'
edit_uri: ''
plugins:
  - search
  # - mkdocs-versioning:
  #     version: 1.0.0

nav:
  - Home: 'index.md'
  - Files: 'tring.md'
  - Version: '../'

```
The site build properly when I comment the lines: 

 `- mkdocs-versioning:
         version: 1.0.0
`

But I cannot see the folder structure like https://github.com/zayd62/mkdocs-versioning-test

I am not using gh-pages or git. This is just static site. 

Pip Freeze:
Markdown==3.2.1
mkdocs==1.1
Python==3.7.4
mkdocs-versioning==0.1.0

Any help will be appreciated. Thanks
