### ISSUE TITLE
Compatibility to awesome-pages

### ISSUE THREAD

**Issue by neatc0der** [zayd62/mkdocs-versioning#59]
**Describe the bug**
When using the "Rest" feature of [awesome-pages](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/), an `AttributeError` occurs in [entry.py:47](https://github.com/zayd62/mkdocs-versioning/blob/387ccd966289bf142fd45df94110a43766867a10/mkversion/entry.py#L47):
> `AttributeError: 'str' object has no attribute 'keys'`

As you can see, the ellipsis within the `nav` section (see below) causes the error.

**To Reproduce**
1. In addition to `mkdocs` and `mkdocs-versioning`, please install `mkdocs-awesome-pages-plugin`
2. Use `mkdocs.yml`:
```yaml
site_name: Sample Project
nav:
  - Home: index.md
  - ...
  - "Version Selector": "../"
plugins:
  - search
  - mkdocs-versioning:
      version: "1.0"
  - awesome-pages
```
3. Run `mkdocs build`

**Expected behavior**
The error should not occur.

**Additional context**
This error is independent of package versions, OS and other external factors.
